//
// Autogenerated by Thrift Compiler (0.9.3)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./canvas_types');
//HELPER FUNCTIONS AND STRUCTURES

CanvasServer_draw_args = function(args) {
  this.opts = null;
  if (args) {
    if (args.opts !== undefined && args.opts !== null) {
      this.opts = args.opts;
    }
  }
};
CanvasServer_draw_args.prototype = {};
CanvasServer_draw_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.opts = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

CanvasServer_draw_args.prototype.write = function(output) {
  output.writeStructBegin('CanvasServer_draw_args');
  if (this.opts !== null && this.opts !== undefined) {
    output.writeFieldBegin('opts', Thrift.Type.STRING, 1);
    output.writeString(this.opts);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

CanvasServer_draw_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
CanvasServer_draw_result.prototype = {};
CanvasServer_draw_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

CanvasServer_draw_result.prototype.write = function(output) {
  output.writeStructBegin('CanvasServer_draw_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

CanvasServerClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
CanvasServerClient.prototype = {};
CanvasServerClient.prototype.seqid = function() { return this._seqid; }
CanvasServerClient.prototype.new_seqid = function() { return this._seqid += 1; }
CanvasServerClient.prototype.draw = function(opts, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_draw(opts);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_draw(opts);
  }
};

CanvasServerClient.prototype.send_draw = function(opts) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('draw', Thrift.MessageType.CALL, this.seqid());
  var args = new CanvasServer_draw_args();
  args.opts = opts;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

CanvasServerClient.prototype.recv_draw = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new CanvasServer_draw_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('draw failed: unknown result');
};
CanvasServerProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
CanvasServerProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

CanvasServerProcessor.prototype.process_draw = function(seqid, input, output) {
  var args = new CanvasServer_draw_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.draw.length === 1) {
    Q.fcall(this._handler.draw, args.opts)
      .then(function(result) {
        var result = new CanvasServer_draw_result({success: result});
        output.writeMessageBegin("draw", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("draw", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.draw(args.opts, function (err, result) {
      if (err == null) {
        var result = new CanvasServer_draw_result((err != null ? err : {success: result}));
        output.writeMessageBegin("draw", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("draw", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

